DROP TABLE IF EXISTS `schedule`;
CREATE TABLE schedule (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, schedule_date DATE NOT NULL, officer_id INT NOT NULL, unit_id INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = '' ;
LOCK TABLES `schedule` WRITE;
ALTER TABLE `schedule` DISABLE KEYS;
ALTER TABLE `schedule` ENABLE KEYS;
UNLOCK TABLES;
DROP TABLE IF EXISTS `personal_access_tokens`;
CREATE TABLE personal_access_tokens (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, tokenable_type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, tokenable_id BIGINT UNSIGNED NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, token VARCHAR(64) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, abilities TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, last_used_at DATETIME DEFAULT NULL, expires_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX personal_access_tokens_token_unique (token), INDEX personal_access_tokens_tokenable_type_tokenable_id_index (tokenable_type, tokenable_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = '' ;
LOCK TABLES `personal_access_tokens` WRITE;
ALTER TABLE `personal_access_tokens` DISABLE KEYS;
ALTER TABLE `personal_access_tokens` ENABLE KEYS;
UNLOCK TABLES;
DROP TABLE IF EXISTS `password_reset_tokens`;
CREATE TABLE password_reset_tokens (email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, token VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT NULL, PRIMARY KEY(email)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = '' ;
DROP TABLE IF EXISTS `failed_jobs`;
CREATE TABLE failed_jobs (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, uuid VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, connection TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, queue TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, payload LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, exception LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, failed_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX failed_jobs_uuid_unique (uuid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = '' ;
DROP TABLE IF EXISTS `users`;
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, username VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, role VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, password VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, remember_token VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX users_username_unique (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = '' ;
LOCK TABLES `users` WRITE;
ALTER TABLE `users` DISABLE KEYS;
INSERT INTO `users` (`id`, `name`, `username`, `role`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('2', 'Enola Mraz PhD', 'admin2', NULL, 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', NULL, '2023-12-02 15:02:37', '2023-12-02 15:11:47');
ALTER TABLE `users` ENABLE KEYS;
UNLOCK TABLES;
DROP TABLE IF EXISTS `result`;
CREATE TABLE result (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, assessment_date DATE NOT NULL, officer_id INT NOT NULL, result INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = '' ;
LOCK TABLES `result` WRITE;
ALTER TABLE `result` DISABLE KEYS;
INSERT INTO `result` (`id`, `assessment_date`, `officer_id`, `result`, `created_at`, `updated_at`) VALUES ('24', '2023-12-02', '1', '4', '2023-12-02 09:43:44', '2023-12-02 09:43:44');
INSERT INTO `result` (`id`, `assessment_date`, `officer_id`, `result`, `created_at`, `updated_at`) VALUES ('25', '2023-12-02', '1', '5', '2023-12-02 09:43:56', '2023-12-02 09:43:56');
ALTER TABLE `result` ENABLE KEYS;
UNLOCK TABLES;
DROP TABLE IF EXISTS `officer`;
CREATE TABLE officer (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, unit_id INT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, nick_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, nip VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, department VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, foto VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT 'no-profil.png' NOT NULL COLLATE `utf8mb4_unicode_ci`, active VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT 'true' COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = '' ;
LOCK TABLES `officer` WRITE;
ALTER TABLE `officer` DISABLE KEYS;
ALTER TABLE `officer` ENABLE KEYS;
UNLOCK TABLES;
DROP TABLE IF EXISTS `migrations`;
CREATE TABLE migrations (id INT UNSIGNED AUTO_INCREMENT NOT NULL, migration VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, batch INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = '' ;
LOCK TABLES `migrations` WRITE;
ALTER TABLE `migrations` DISABLE KEYS;
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('1', '2014_10_12_000000_create_users_table', '1');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('2', '2014_10_12_100000_create_password_reset_tokens_table', '1');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('3', '2019_08_19_000000_create_failed_jobs_table', '1');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('4', '2019_12_14_000001_create_personal_access_tokens_table', '1');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('5', '2023_11_19_202602_create_level_table', '2');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('6', '2023_11_19_205427_create_unit_table', '3');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('8', '2023_11_19_205847_create_schedule_table', '3');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('10', '2023_11_19_205956_create_result_table', '4');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('13', '2023_12_02_074153_create_signers_table', '6');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('15', '2023_11_19_205529_create_officer_table', '7');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('16', '2023_12_02_081549_add_active_to_officer_table', '7');
ALTER TABLE `migrations` ENABLE KEYS;
UNLOCK TABLES;
DROP TABLE IF EXISTS `level`;
CREATE TABLE level (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, level_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = '' ;
LOCK TABLES `level` WRITE;
ALTER TABLE `level` DISABLE KEYS;
INSERT INTO `level` (`id`, `level_name`, `created_at`, `updated_at`) VALUES ('1', 'admin', NULL, NULL);
INSERT INTO `level` (`id`, `level_name`, `created_at`, `updated_at`) VALUES ('2', 'kepaniteraan', NULL, NULL);
INSERT INTO `level` (`id`, `level_name`, `created_at`, `updated_at`) VALUES ('3', 'kesekretariatan', NULL, NULL);
INSERT INTO `level` (`id`, `level_name`, `created_at`, `updated_at`) VALUES ('4', 'meja_ecourt', NULL, NULL);
INSERT INTO `level` (`id`, `level_name`, `created_at`, `updated_at`) VALUES ('5', 'informasi', NULL, NULL);
ALTER TABLE `level` ENABLE KEYS;
UNLOCK TABLES;
DROP TABLE IF EXISTS `signers`;
CREATE TABLE signers (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, nip VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, department VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = '' ;
LOCK TABLES `signers` WRITE;
ALTER TABLE `signers` DISABLE KEYS;
ALTER TABLE `signers` ENABLE KEYS;
UNLOCK TABLES;
DROP TABLE IF EXISTS `unit`;
CREATE TABLE unit (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, unit_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = '' ;
LOCK TABLES `unit` WRITE;
ALTER TABLE `unit` DISABLE KEYS;
INSERT INTO `unit` (`id`, `unit_name`, `created_at`, `updated_at`) VALUES ('1', 'Kepaniteraan', NULL, NULL);
INSERT INTO `unit` (`id`, `unit_name`, `created_at`, `updated_at`) VALUES ('2', 'Kesekretariatan', NULL, NULL);
INSERT INTO `unit` (`id`, `unit_name`, `created_at`, `updated_at`) VALUES ('3', 'Meja Ecourt', NULL, NULL);
INSERT INTO `unit` (`id`, `unit_name`, `created_at`, `updated_at`) VALUES ('4', 'Meja Informasi dan Pengaduan', NULL, NULL);
ALTER TABLE `unit` ENABLE KEYS;
UNLOCK TABLES;
